# Generated by Django 5.0.4 on 2024-06-02 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientType', models.CharField(max_length=100)),
                ('ClientName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('RepresentativeName', models.CharField(max_length=100)),
                ('BusinessRegistrationNumber', models.CharField(max_length=100)),
                ('ClientAddress', models.CharField(max_length=100)),
                ('ClientPhone', models.CharField(max_length=100)),
                ('PersonInCharge', models.CharField(max_length=100)),
                ('PersonInChargePhone', models.CharField(max_length=100)),
                ('FirstTradeDate', models.DateField()),
                ('LastTradeDate', models.DateField()),
                ('Payment_Delivery', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAccident',
            fields=[
                ('WaybillNo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Recipient', models.CharField(max_length=100)),
                ('TotalFreight', models.IntegerField(default=0)),
                ('ProductValue', models.IntegerField(default=0)),
                ('Reimbursement', models.IntegerField(default=0)),
                ('ShippingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('ETA', models.DateField()),
                ('OrderWeight', models.IntegerField(max_length=100)),
                ('Part', models.CharField(max_length=100)),
                ('OderPrice', models.IntegerField(default=0)),
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderSituation', models.CharField(max_length=100)),
                ('OrderFix', models.BooleanField(default=False)),
                ('Client', models.ForeignKey(db_column='ClientName', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('StockDate', models.DateTimeField(auto_now_add=True)),
                ('Stockitem', models.CharField(max_length=100)),
                ('RealWeight', models.IntegerField(default=0)),
                ('RealPrice', models.IntegerField(default=0)),
                ('MeterialNo', models.IntegerField(default=0)),
                ('SlaugtherDate', models.DateField()),
                ('UnitPrice', models.IntegerField(default=0)),
                ('StockNo', models.IntegerField(primary_key=True, serialize=False)),
                ('StockSituation', models.CharField(max_length=100)),
                ('StockFix', models.BooleanField(default=False)),
                ('OrderNo', models.ForeignKey(db_column='OrderNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductDate', models.DateTimeField(auto_now_add=True)),
                ('WeightAfterWork', models.IntegerField(default=0)),
                ('LossWeight', models.IntegerField(default=0)),
                ('ProductPrice', models.IntegerField(default=0)),
                ('DiscountRate', models.IntegerField(default=0)),
                ('ProductNo', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('ProductSituation', models.CharField(max_length=100)),
                ('ProductFix', models.BooleanField(default=False)),
                ('Quantity', models.IntegerField(default=0)),
                ('OrderNo', models.ForeignKey(db_column='OrderNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.order')),
                ('StockNo', models.ForeignKey(db_column='StockNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('empNo', models.CharField(max_length=10, unique=True, verbose_name='Employee Number')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='User name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('Job', models.CharField(choices=[('OM', '주문담당자'), ('DM', '해체담당자'), ('WM', '입고담당자')], default='OM', max_length=50)),
                ('Position', models.CharField(choices=[('A', '관리자'), ('M', '매니저'), ('U', '사용자')], default='U', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='StockWorker',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('PurchaseDate', models.DateTimeField(auto_now_add=True)),
                ('PurchaseAddress', models.CharField(max_length=100)),
                ('PurchasePhone', models.CharField(max_length=100)),
                ('PurchaseNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Wrapping', models.BooleanField(default=False)),
                ('ProductNo', models.ForeignKey(db_column='ProductNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.product')),
                ('Purchaser', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ProductWorker',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='OrderWorker',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
