# Generated by Django 5.0.6 on 2024-05-21 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('OrderWeight', models.CharField(max_length=100)),
                ('ETA', models.DateField()),
                ('Part', models.CharField(max_length=100)),
                ('Client', models.CharField(max_length=100)),
                ('OderPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=6, unique=True)),
                ('EmpNo', models.CharField(editable=False, max_length=6, unique=True)),
                ('Job', models.CharField(choices=[('OM', '주문담당자'), ('DM', '해체담당자'), ('WM', '입고담당자')], default='OM', max_length=100)),
                ('Position', models.CharField(choices=[('A', '관리자'), ('M', '매니저'), ('U', '사용자')], default='U', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('StockNo', models.IntegerField(primary_key=True, serialize=False)),
                ('StockDate', models.DateTimeField(auto_now_add=True)),
                ('RealWeight', models.IntegerField(default=0)),
                ('MeterialNo', models.IntegerField(default=0)),
                ('SlaugtherDate', models.DateField()),
                ('UnitPrice', models.IntegerField(default=0)),
                ('SaleApply', models.BooleanField(default=False)),
                ('FinalPrice', models.IntegerField(default=0)),
                ('OrderNo', models.ForeignKey(db_column='OrderNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.order')),
                ('EmpNo', models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductDate', models.DateTimeField(auto_now_add=True)),
                ('AfterProduceWeight', models.IntegerField(default=0)),
                ('RemainWeight', models.IntegerField(default=0)),
                ('ProduceAmount', models.IntegerField(default=0)),
                ('SalePrice', models.IntegerField(default=0)),
                ('StockNo', models.ForeignKey(db_column='StockNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.stock')),
                ('EmpNo', models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='EmpNo',
            field=models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
