# Generated by Django 5.0.4 on 2024-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderSituation',
            field=models.CharField(max_length=10),
        ),
    ]
