# Generated by Django 5.0.4 on 2024-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderWeight',
            field=models.CharField(max_length=100),
        ),
    ]
