# Generated by Django 5.0.4 on 2024-06-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaccident',
            name='PurchaseDate',
            field=models.ForeignKey(db_column='PurchaseDate', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.purchase', to_field='PurchaseNo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ProductNo',
            field=models.ForeignKey(db_column='ProductNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.product', to_field='ProductNo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Purchaser',
            field=models.ForeignKey(db_column='Purchaser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='empNo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='OrderNo',
            field=models.ForeignKey(db_column='OrderNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.order', to_field='OrderNo', unique=True),
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
                ('SubsidiaryMaterial', models.CharField(max_length=100)),
                ('Quntity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('TotalPrice', models.IntegerField(default=0)),
                ('CostSituation', models.CharField(max_length=100)),
                ('Client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.client', to_field='ClientName')),
            ],
        ),
    ]
