# Generated by Django 5.0.4 on 2024-06-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='OrderNo',
            field=models.ForeignKey(db_column='OrderNo', on_delete=django.db.models.deletion.CASCADE, to='MeatApp.order', to_field='OrderNo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='StockDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='StockNo',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
