# Generated by Django 5.0.4 on 2024-06-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0002_alter_order_ordersituation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
