# Generated by Django 5.0.4 on 2024-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0002_alter_order_orderweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OderPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='AfterProduceWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProduceAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='RemainWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='SalePrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='FinalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='MeterialNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='RealWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='UnitPrice',
            field=models.IntegerField(default=0),
        ),
    ]
