# Generated by Django 5.0.4 on 2024-06-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0003_alter_product_productdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
