# Generated by Django 5.0.4 on 2024-06-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0003_order_adddatetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-addDateTime']},
        ),
    ]
