# Generated by Django 5.0.4 on 2024-06-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0004_alter_product_productdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-ProductDate']},
        ),
    ]
