# Generated by Django 5.0.4 on 2024-09-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeatApp', '0007_purchase_purchasername_purchase_purchaserprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PurchaseDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PurchaserName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PurchaserPrice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
