# Generated by Django 5.0.4 on 2024-04-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('EmpNo', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=100)),
                ('Job', models.CharField(choices=[('OM', '주문담당자'), ('DM', '해체담당자'), ('WM', '입고담당자')], default='OM', max_length=100)),
                ('Position', models.CharField(choices=[('A', '관리자'), ('M', '매니저'), ('U', '사용자')], default='U', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassWord', models.CharField(max_length=100)),
                ('EmpNo', models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to='elections.empinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('OrderWeight', models.CharField(max_length=100)),
                ('ETA', models.DateField()),
                ('Part', models.CharField(max_length=100)),
                ('Client', models.CharField(max_length=100)),
                ('OderPrice', models.IntegerField(default=0)),
                ('EmpNo', models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to='elections.empinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('StockNo', models.IntegerField(primary_key=True, serialize=False)),
                ('StockDate', models.DateTimeField(auto_now_add=True)),
                ('RealWeight', models.IntegerField(default=0)),
                ('MeterialNo', models.IntegerField(default=0)),
                ('SlaugtherDate', models.DateField()),
                ('UnitPrice', models.IntegerField(default=0)),
                ('SaleApply', models.BooleanField(default=False)),
                ('FinalPrice', models.IntegerField(default=0)),
                ('EmpNo', models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to='elections.empinfo')),
                ('OrderNo', models.ForeignKey(db_column='OrderNo', on_delete=django.db.models.deletion.CASCADE, to='elections.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductDate', models.DateTimeField(auto_now_add=True)),
                ('AfterProduceWeight', models.IntegerField(default=0)),
                ('RemainWeight', models.IntegerField(default=0)),
                ('ProduceAmount', models.IntegerField(default=0)),
                ('SalePrice', models.IntegerField(default=0)),
                ('EmpNo', models.ForeignKey(db_column='EmpNo', on_delete=django.db.models.deletion.CASCADE, to='elections.empinfo')),
                ('StockNo', models.ForeignKey(db_column='StockNo', on_delete=django.db.models.deletion.CASCADE, to='elections.stock')),
            ],
        ),
    ]
